name: <Plugin Name>
author: <Your Name>
main: me.<Your Name>.<Plugin Name>.<Plugin Name>
version: 1.0
database: false
description: >
             A <Plugin Name> plugin for Bukkit.

commands:
  <Plugin Name>:
    description: Shows the version of the plugin.
    usage: |
           You typed the command incorrectly.
           For help type /<command> help.