name: Template
author: Tagette
main: me.tagette.template.Template
version: 1.0
database: false
description: >
             A template plugin for Bukkit.

commands:
  template:
    # Class is required for command to work
    class: me.tagette.template.commands.TemplateCmd
    description: Handles the commands of the plugin.
    usage: |
           You typed the command incorrectly.
           For help type /<command> help.